### ISSUE TITLE
Add ranges for floats and doubles

### ISSUE THREAD

**Issue by aaron868** [ncredinburgh/QuickTheories#20]
Could you add range constraints on double and float generators similar to those of integers? For example, from().upTo().

Thank you.

**Comment by hcoles** [comment]
Hi @aaron868  - sorry for the slow response on this.

The 0.23 release added upToAndIncluding ranges for doubles. upTo ranges are a little problematic as it is not instantly clear what the maximum value they should produce is.

upToAndIncluding will be added for floats in the next release.

**Comment by hcoles** [comment]
This has now been released in 0.24.
