### ISSUE TITLE
shouldIncludeOnlyFirst10ValuesInReport Test failing

### ISSUE THREAD

**Issue by pietomb** [ncredinburgh/QuickTheories#22]
I've forked at checked out the project, when running:
mvn test

It is failing on the following test:
shouldIncludeOnlyFirst10ValuesInReport(org.quicktheories.quicktheories.core.ExceptionReporterTest)

The assertion error is:
 java.lang.AssertionError: 
Expecting:
 <"Property falsified after 0 example(s) 
Smallest found falsifying value(s) :-
0
Other found falsifying value(s) :- 
1
2
3
4
5
6
7
8
9
10
 
Seed was 0">
to contain:
 <"1
2
3
4
5
6
7
8
9
10">

**Comment by pietomb** [comment]
It seems that it's because the expected.getMessage() has:
1\r\n2\r\n.....
Rather than without the \r

Is this down to the environment it's running in?

**Comment by hcoles** [comment]
Could well be - think it has only ever been built on Llnux machines (and possibly a mac).
